config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  RATINGS = %w(G PG PG-13 R NC-17) # possible movie ratings

  # a movie "flops" if it's gross rev is less than $225M
  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  # order with most-recent release first
  def self.released
    where("released_on < ?", Time.now).order(released_on: :desc)
  end

  # model validation
  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }
  validates :rating, inclusion: { in: RATINGS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released # only display released movies
    # @movies = Movie.all
  end

  # displays one film in a separate page using primary key
  def show
    @movie = Movie.find(params[:id])
  end

  # edit one film as admin
  def edit
    @movie = Movie.find(params[:id])
  end

  # patch a movie
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  # add a new film page
  def new
    @movie = Movie.new
  end

  # create new film
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully added!"
    else
      render :new
    end
  end

  # delete a film
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!" # redirect to /movies
  end

  private

  private

    # allow manipulation of all fields for now
    def movie_params
      params.require(:movie).
        permit(:title, :description, :rating, :released_on,
          :total_gross, :director, :duration, :image_file_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  # if a movie grosses less than $225M, it's a flop
  def total_gross(movie)
    if movie.flop?
      "Flop!"
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  # display first 140 characters of movie description
  def description(movie)
    truncate(movie.description, length: 150, separator: ' ')
  end

  # renders release date in a human-friendly way
  def release_date(movie)
    movie.released_on.strftime("Released %B %-d, %Y")
  end
end

app/views/layouts/_flash.html.erb
<!-- flash notices -->
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made by Kelly Ma.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <!-- logo links to homepage -->
    <%= link_to(image_tag("flixr", size: "65x38", alt: ""), root_path) %>
    <ul>
      <li><%= link_to("All Films", movies_path) %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <%= render "shared/errors", object: movie %>

  <%= form.label :title %>
  <%= form.text_field :title, autofocus: true %>

  <%= form.label :description %>
  <%= form.text_area :description, rows: 10 %>

  <%= form.label :rating %>
  <%= form.select :rating, Movie::RATINGS, prompt: "Select a rating" %>

  <%= form.label :released_on %>
  <%= form.date_select :released_on, {}, {class: "date"} %>

  <%= form.label :director %>
  <%= form.text_field :director %>

  <%= form.label :total_gross %>
  <%= form.number_field :total_gross %>

  <%= form.label :duration %>
  <%= form.text_field :duration %>

  <%= form.label :image_file_name %>
  <%= form.text_field :image_file_name %>

  <%= form.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
    <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to(movie.title, movie) %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <p>
        <%= description(movie) %>
      </p>
    </div>
  </section>
<% end %>

<section class="admin">
  <%= link_to("Add a Film", new_movie_path, class: "button")%>
</section>

app/views/movies/new.html.erb
<h1>Add a Film</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= release_date(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Directed by</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
  <%= link_to "Delete", @event, class: "button", method: :delete,
    data: {confirm: "Are you sure?"} %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your changes could not be saved.
    </h2>
    <h3>
      Please verify the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>